config/routes.rb
Rails.application.routes.draw do
  # pages - класс, который будет обрабатывать входящий запрос;
  # index - метод внутри этого класса pages.
  # Класс и метод лежат по пути: app -> controllers -> pages_controller.rb - название должно содержать название класса
  # + "_controller".
  root 'pages#index'

  # Все нижеперечисленные маршруты можно не прописывать явно, при этом они все отобразятся именно так, как если бы их указывали явно
  # Нужно создать конкретные маршруты для контроллера
  # Для ответов делаем вложенные маршруты
  resources :questions do
    resources :answers, only: %i[create destroy edit update]
  end
  # only: %i[index new edit create update destroy show] - можно не перечислять явно, так как уже создали их и описали (они описываются и подразумеваются по дефолту) 

  # Новый маршрут, который отображает все вопросы, то когда придет GET запрос '/questions', то отправляй в метод контроллера
  #get '/questions', to: 'questions#index'

  # Новый маршрут, по которму можно создать вопрос; создание вопроса обрабатывается методом new в соотв. контроллере
  #get '/questions/new', to: 'questions#new'

  # Новый маршрут, который обрабатывает создание запроса и принимает те параметры, которые мы заполнили в форме создания запроса
  #post '/questions', to: 'questions#create'

  # Новый маршрут, который отображает форму реактирования вопроса
  # :id - подставляется автоматически из БД, о чем говорит ':', что указывает на то что id - это переменная
  #get '/questions/:id/edit', to: 'questions#edit'

  # Добавление пользователей и маршрутов для них
  resources :users, only: %i[new create]
end

# Чтобы посмотреть все пути приложения в консоли выполняем команду: rails routes
# Маршрут = запрос

app/models/question.rb
# ApplicationRecord - позволяет работать с таблицами БД как с классами языка, чтобы не писать сырые sql-запросы
# Тут описывается бизнес-логика работы с данными!
class Question < ApplicationRecord
  # Добавили связь с ответами, указав тип связи, а также удаление связей, чтобы при удалении вопроса удалялись ответы
  has_many :answers, dependent: :destroy

  # Добавим валидацию, чтобы заголовок и тело вопроса не были пустыми
  validates :title, presence: true, length: {minimum: 2}
  validates :body, presence: true, length: {minimum: 2}

  def formatted_created_at
    # Метод, который форматирует дату создания
    # self - явно указывает, что метод вызывается относительно конкретного образца класса (можно не указывать)
    self.created_at.strftime('%Y-%m-%d %H:%M:%S')
  end
end

app/controllers/questions_controller.rb
# Создали контроллер, которые будет отображать все вопросы
class QuestionsController < ApplicationController

  # Вынесем повторяющуюся часть, которая будет выполняться перед нужными методами
  before_action :set_question!, only: %i[show destroy edit update]

  def index
    # Методы вытаскивает из БД все вопросы и запихивает в переменную, которую потом будем использовать для отображения
    # Поменяли с метода от kaminari на pagy
    #@questions = Question.order(created_at: :desc).page params[:page]
    @pagy, @questions = pagy Question.order(created_at: :desc)
  end

  def new
    # Метод создает новый вопрос, а точнее отображает форму создания нового вопроса
    # Сначала инстанцируем (создаем) новый класс-вопрос, пользователь его сам заполняет и после этого сохраняем его, т.е. кладем в БД
    @question = Question.new
    # Заполнение вопросов происходит в форме views -> questions -> new.html.erb
  end

  def create
    # Метод обрабатывает создание нового, а точнее обрабатывает форму создания

    # render - вывод какой-то другой информации, отличной от представлений
    # plain - просто текст (та самая другая инфорация, которую рендерим)
    # params - все параметры запроса, которые пришли
    # render plain: params

    # Нужно создать новый вопрос с параметрами из формы создания, для этого исп приватный метод
    @question = Question.new question_params

    # Создали вопрос, сохраняем его и что-то делаем в зависимости от успешного (или нет) сохранения
    if @question.save
      # Всплывающее окно, что создали новую запись
      # :success - ключ, к которому можно обратиться в форме
      flash[:success] = "Question created!"
      # Если сохранили, то перенаправляем на другую страницу - страницу всех вопросов
      redirect_to questions_path
    else
      # Если сохранить не удалось, тогда еще раз отрендерить представление (view) new.html.erb
      render :new
    end
  end

  def edit
    # Метод для изменения вопроса, а точнее отображает форму редактирования
    # Ищем вопрос, который надо изменить
    # id: - то поле в БД, по которому осуществляется поиск
    # params - объект, где лежат все параметры запроса
    # [:id] - параметр запроса, который берется из url
    # Перенесли в set_question
    # @question = Question.find_by id: params[:id]
  end

  def update
    # Метод для изменения вопроса, а точнее обрабатывает форму редактирования
    # Ищем вопрос, который надо изменить
    # Перенесли в set_question
    # @question = Question.find_by id: params[:id]
    # Изменили вопрос, запихнули в него новые параметры и обновляем его
    if @question.update question_params
      flash[:success] = "Question updated!"
      # Если сохранили, то перенаправляем на другую страницу - страницу всех вопросов
      redirect_to questions_path
    else
      # Если сохранить не удалось, тогда еще раз отрендерить представление (view) new.html.erb
      render :edit
    end
  end

  def destroy
    # Метод для удаления вопросов, втч из БД
    # Перенесли в set_question
    # @question = Question.find_by id: params[:id]
    @question.destroy
    flash[:success] = "Question deleted!"

    redirect_to questions_path
  end

  def show
    # Метод для просмотра вопроса, т.е. отображение формы просмотра
    # Перенесли в set_question
    #@question = Question.find_by id: params[:id]
    # Привязываем ответ к вопросу
    @answer = @question.answers.build
    # Отображение ответов к конкретному вопросу (:desc - сортировка по убыванию - новый наверху)
    # @answers = @question.answers.order(created_at: :desc).page(params[:page]).per(5)
    # @answers = Answer.where(question: @question).order created_at: :desc
    # Аналогично меняем для ответов пагинацию
    @pagy, @answers = pagy @question.answers.order(created_at: :desc)
  end

  private
  def question_params
    # Метод просто достает title и body вопроса из параметров для дальнейшей работы с ними
    # permit - разрешает создать и работать с теми параметрами, которые мы явно указали - защита от дурака, чтобы не меняли то, что не надо
    params.require(:question).permit(:title, :body)
  end

  def set_question!
    # Добавили обработку ошибок в случае, если id не существует
    @question = Question.find params[:id]
  end
end

# Методы index, new (по уолчанию)- выдают содержимое наших представлений (views)
# Для иных действий (вывода чего-то иного) используется метод 'render'

app/views/questions/_form.html.erb
<!-- Нижнее подчеркивание говорит о том, что этот файл - частичное (partial) представление
рендериться само по себе, но не вставляется в layout-->

<!-- Создаем форму заполнения через руби, т.е. код сам создаст теги и разметку --> 

<%= render 'shared/errors', object: @question %>

<%= form_with model: @question do |f| %>
  <div class="mb-3 row">

    <!-- Указываем наименование поля, а так же параметры этого поля: мин. длина, не пустое, плейсхолдер -->
    <div class="col-sm-2 col-form-label">
      <%= f.label :title %>
    </div>

    <div class="col-sm-10">
      <%= f.text_field :title, placeholder: "Title", class: 'form-control' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>

    <div class="col-sm-10">
      <%= f.text_area :body, class: 'form-control' %>
    </div>
  </div>

  <%= f.submit "Submit question!", class: 'btn btn-primary' %>
<% end %>

app/views/questions/edit.html.erb
<!-- Ссылка на локальный yield - название вкладки -->
<% provide :page_title, 'Edit question' %>

<% currently_at 'Questions' %>

<h1 class="mb-4">Edit question</h1>

<!-- Когда есть повторяющиеся страницы или элементы страниц, то их можно объеденить и рендерить с
помощью специальных partial представлений. Можно указывать файлы из других директорий: <directory_name>/_<file_name>-->
<%= render 'form' %>

app/views/questions/index.html.erb
<!-- Ссылка на локальный yield - название вкладки -->
<% provide :page_title, 'Questions' %>
<% currently_at 'Questions' %>
<h1 class="mb-4"> Questions</h1>

<%= link_to 'New question', new_question_path, class: 'btn btn-primary btn-lg mb-3' %>

<%== pagy_bootstrap_nav @pagy %>

<% @questions.each do |question| %>
  <article class="card my-3">
    <div class="card-body">
      <h4> <%= question.title  %></h4>

      <section class="card-text">
        <time datetime="<%= question.formatted_created_at %>">
          <small><%= question.formatted_created_at %></small>
        </time>

        <p>
          <!-- Добавили helper 'strip_tags', который удаляет все теги из тела вопроса в данной форме-->
          <!-- Добавили 'truncate', который устанавливает ограничение по длине и продолжение -->
          <%= truncate strip_tags(question.body), length: 150, omission: '... (continued)' %>
        </p>
      </section>

        <!-- Форма просмотра -->
        <%= link_to 'Show', question_path(question), class: 'btn btn-primary' %>
        <!-- edit_question_path(@question) - передаем переменную question, чтобы передать параметры из url запроса -->
        <%= link_to 'Edit', edit_question_path(question), class: 'btn btn-secondary' %>
        <!-- Необходимо помимо пути указать метод HTTP delete, чтобы указать, что надо удалить данные -->
        <%= link_to 'Destroy', question_path(question), class: 'btn btn-danger',
        data: {method: :delete, confirm: "?"} %>
      
    </div>
  </article>
<% end %>

<%== pagy_bootstrap_nav @pagy %>

app/views/questions/new.html.erb
<!-- Ссылка на локальный yield - название вкладки -->
<% provide :page_title, 'New question' %>
<% currently_at 'Answers' %>

<h1 class="mb-4">New question</h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<% provide :page_title, "#{@question.title}" %>
<% currently_at 'Questions' %>

<h1 class="mb-4"><%= @question.title %></h1>


<time datetime="<%= @question.formatted_created_at %>">
    <%= @question.formatted_created_at %>
</time>

<div class="lead my-3">
    <!-- Добавили обработчик тегов
     sanitize - helper, который позволяет использовать теги только для -->
    <%= sanitize @question.body %>
</div>

<%= link_to 'Show', question_path(@question), class: 'btn btn-primary' %>
<!-- edit_question_path(@question) - передаем переменную question, чтобы передать параметры из url запроса -->
<%= link_to 'Edit', edit_question_path(@question), class: 'btn btn-secondary' %>
<!-- Необходимо помимо пути указать метод HTTP delete, чтобы указать, что надо удалить данные -->
<%= link_to 'Destroy', question_path(@question), class: 'btn btn-danger',
data: {method: :delete, confirm: "?"} %>

<!-- Отображение формы для заполнения ответов -->
<hr class="my-3">

<h2 class="my-3">Write your answer</h2>

<%= render 'answers/form' %>

<!-- Отображение списка объектов -->
<h2 class="mt-5">Answers</h2>

<!-- Убираем за ненадобностью -->
<%# @answers.each do |answer| %>
  <!-- Перенесли в partial _answer, а рендер сам все сделает и отрендерит каждый элемент коллекции -->
<%# end %>

<%== pagy_bootstrap_nav @pagy %>
<!-- Уходим от глобального использования @questions, а передаем как локальную переменную -->
<%= render partial: 'answers/answer', collection: @answers, as: :answer, locals: {question: @question}%>

<%== pagy_bootstrap_nav @pagy %>