config/routes.rb
Rails.application.routes.draw do
  # pages - класс, который будет обрабатывать входящий запрос;
  # index - метод внутри этого класса pages.
  # Класс и метод лежат по пути: app -> controllers -> pages_controller.rb - название должно содержать название класса
  # + "_controller".
  root 'pages#index'

  # Все нижеперечисленные маршруты можно не прописывать явно, при этом они все отобразятся именно так, как если бы их указывали явно
  # Нужно создать конкретные маршруты для контроллера
  # Для ответов делаем вложенные маршруты
  resources :questions do
    resources :answers, only: %i[create destroy edit update]
  end
  # only: %i[index new edit create update destroy show] - можно не перечислять явно, так как уже создали их и описали (они описываются и подразумеваются по дефолту) 

  # Новый маршрут, который отображает все вопросы, то когда придет GET запрос '/questions', то отправляй в метод контроллера
  #get '/questions', to: 'questions#index'

  # Новый маршрут, по которму можно создать вопрос; создание вопроса обрабатывается методом new в соотв. контроллере
  #get '/questions/new', to: 'questions#new'

  # Новый маршрут, который обрабатывает создание запроса и принимает те параметры, которые мы заполнили в форме создания запроса
  #post '/questions', to: 'questions#create'

  # Новый маршрут, который отображает форму реактирования вопроса
  # :id - подставляется автоматически из БД, о чем говорит ':', что указывает на то что id - это переменная
  #get '/questions/:id/edit', to: 'questions#edit'

  # Добавление пользователей и маршрутов для них
  resources :users, only: %i[new create]
end

# Чтобы посмотреть все пути приложения в консоли выполняем команду: rails routes
# Маршрут = запрос

app/views/shared/_errors.html.erb
<% if object.errors.full_messages.any? %>
  <div class="alert alert-danger">
    <ul class="mb=0">
      <% object.errors.full_messages.each do |msg| %>
        <li> <%= msg %></li>
      <% end %> 
    </ul>
  </div>
<% end %>

app/views/shared/_menu.html.erb
<!-- Указываем, в какой yield нам надо вывести -->
<% provide :main_menu do%>
  <header class="p-3 bg-dark text-white">
    <div class="container">
      <!--Добавили навигацию для всех страниц-->
      <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <!--Для ссылок будем использовать именованные ссылки ruby on rails-->
          <!--Каждый маршрут имеет название, которое можно посмотреть в консоли командой 'rails routes' в столбце Prefix + '_path'-->
          <li><%= nav_tab 'Home', root_path,
                          class: 'nav-link px-2',
                          current_page: current_page %></li>
          <li><%= nav_tab 'Questions', questions_path,
                          class: 'nav-link px-2',
                          current_page: current_page %></li>
        </ul>
        <ul class="nav col-12 col-lg-auto mb-2 mb-md-0">
          <% if user_signed_in? %>
            <li>
              <a class="nav-link px-2 text-white" href="#">
                <%= current_user.name %>
              </a>
            </li>
          <% else %>
            <li><%= nav_tab 'Sign Up', new_user_path,
                            class: 'nav-link px-2',
                            current_page: current_page%></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>
<% end %>